spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    jdbc-url: jdbc:mysql://r.erst.kr:12304/solugate
    username: dev
    password: ers0212!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true


